### ISSUE TITLE
Images from Discord's CDN do not display

### ISSUE THREAD

**Issue by benjidial** [ChickenSaysBak/ChatImage#1]
Hello, this plugin is very nice! I just installed it today and I noticed an issue: when an image is uploaded to Discord, the URL it gets is `https://cdn.discordapp.com/[...]/[something].png?[some query information]`. The plugin strips this query information in the `stripURL` function, but Discord's CDN only serves the image if this query information is present. It seems like removing the call to `stripURL` in the `findURL` function would solve this, but I am unable to test that since I get a Maven error about a dependency for DiscordSRV when trying to compile. A comment says the stripping is need for moderatecontent.com, and I'm guessing you wouldn't want to allow everything that has ever been uploaded to Discord to come through unmoderated, so maybe the query stripping could just be disabled when moderation is disabled?

Again, very nice plugin!

**Comment by ChickenSaysBak** [comment]
Thanks for pointing this out! Resolved here: 0d122b0f74e2dda0ae335b6f6b015c9d7cae101d

Consider leaving a review on Spigot if you like the plugin 😃
