### ISSUE TITLE
Add GIF Support

### ISSUE THREAD

**Issue by Cyberillc** [ChickenSaysBak/ChatImage#4]
I thought it would be great to incorporate gif support as they consist of images with frames.
You could draw inspiration from this library.
Bukkit: (https://bukkit.org/threads/lib-imagemessage-v2-1-send-images-to-players-via-the-chat.204902/)
Source: (https://github.com/arxenix/ImageMessage)

**Comment by ChickenSaysBak** [comment]
Thank you for the suggestion. Unfortunately, I do not plan to add this as the only way to implement it would be to spam players' chat with the frames. I feel like this feature would be more inconvenient than it is helpful. If you have suggestions for better ways to implement it, I'm all ears. 🙂

**Comment by ChickenSaysBak** [comment]
Animated GIFs have been added in version 3.0.0! This is thanks to the addition of dialogs in MC version 1.21.6.
